# Rename this file to local_env.yml
# Add account settings and API keys here.
# This file should be listed in .gitignore to keep your settings secret!
# Each entry gets set as a local environment variable.
# This file overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: 'Your_Gmail_Username'
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# G-Mail Configuration 

FEEDBACK_EMAIL_FROM: 'gshackathon@gmail.com>'
FEEDBACK_EMAIL_TO: 'gshackathon@gmail.com'
ADMIN_SMTP_ADDRESS: 'smtp.gmail.com'
ADMIN_SMTP_PORT: '587'
ADMIN_EMAIL_DOMAIN: 'gmail.com'
ADMIN_EMAIL_USER: 'gshackathon@gmail.com'
ADMIN_EMAIL_PASSWORD: 'gshackathon13'
